---
efi:
  mountPoint: /boot/efi
  recommendedSize: 512MiB
  minimumSize: 512MiB
  label: EFI
userSwapChoices: [ none ]
initialSwapChoice: none
initialPartitioningChoice: none
defaultPartitionTableType: gpt
requiredPartitionTableType: gpt
defaultFileSystemType: ext4
availableFileSystemTypes: [ ext4 ]
allowManualPartitioning: false
enableLuksAutomatedPartitioning: false
showNotEncryptedBootMessage: false
requiredStorage: 12
lvm:
  enable: false
essentialMounts: [ "live-*", control, ventoy ]
