---
units:
  - name: NetworkManager.service
    action: enable
    mandatory: true
  - name: NetworkManager-wait-online.service
    action: disable
    mandatory: true
  - name: fstrim.timer
    action: enable
    mandatory: true
  - name: seatd.service
    action: enable
    mandatory: true
  - name: frostbite-firstboot.service
    action: enable
    mandatory: true
  - name: frostbite-performance.service
    action: enable
    mandatory: true
  - name: getty@tty1.service
    action: enable
    mandatory: true
