#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
manifest_dir="$repo_root/manifests"
out_file="$repo_root/archiso/packages.x86_64"

manifests=(
  "$manifest_dir/base.packages"
  "$manifest_dir/gaming-core.packages"
  "$manifest_dir/drivers-amd-intel.packages"
  "$manifest_dir/installer.packages"
)

if [[ "${INCLUDE_NVIDIA:-0}" == "1" ]]; then
  manifests+=("$manifest_dir/drivers-nvidia.packages")
fi

if [[ "${INCLUDE_EMULATION:-0}" == "1" ]]; then
  manifests+=("$manifest_dir/optional-emulation.packages")
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

for manifest in "${manifests[@]}"; do
  if [[ ! -f "$manifest" ]]; then
    echo "missing manifest: $manifest" >&2
    exit 1
  fi
  sed -E 's/#.*$//' "$manifest" | awk 'NF { print $1 }' >> "$tmp"
done

{
  echo "# Generated by scripts/compose-packages.sh."
  echo "# INCLUDE_NVIDIA=${INCLUDE_NVIDIA:-0} INCLUDE_EMULATION=${INCLUDE_EMULATION:-0}"
  sort -u "$tmp"
} > "$out_file"

echo "wrote $out_file"
