---
backend: pacman
operations:
  - try_install:
      - linux-zen
      - linux-zen-headers
      - steam
      - gamescope
      - gamemode
      - mangohud
  - remove:
      - arch-install-scripts
