---
defaultGroups:
  - name: wheel
    must_exist: true
    system: true
  - name: video
    must_exist: true
    system: true
  - name: audio
    must_exist: true
    system: true
  - name: input
    must_exist: true
    system: true
  - name: storage
    must_exist: true
    system: true
  - name: power
    must_exist: true
    system: true
  - name: seat
    must_exist: true
    system: true
sudoersGroup: wheel
sudoersConfigureWithGroup: true
autologinGroup: ""
displayAutologin: false
doAutologin: true
setRootPassword: false
doReusePassword: false
allowWeakPasswords: false
allowWeakPasswordsDefault: false
passwordRequirements:
  minLength: 8
  maxLength: 128
  libpwquality:
    - minlen=8
user:
  shell: /bin/bash
  forbidden_names: [ root, frostbite ]
  home_permissions: "0700"
  nopasswd_group: ""
hostname:
  location: EtcFile
  writeHostsFile: true
  template: "frostbite-${login}"
  forbidden_names: [ localhost ]
allowActiveDirectory: false
