---
showSupportUrl: false
showKnownIssuesUrl: false
requirements:
  requiredStorage: 4
  requiredRam: 4
  check:
    - storage
    - ram
    - root
    - screen
    - internet
  required:
    - storage
    - ram
    - root
  internetCheckUrl: https://archlinux.org
